In [76]:
'''
Basic data cleaning notebook
'''
import sqlite3
import pandas as pd
import sys
if '..' not in sys.path:
    sys.path.insert(0, '..')
from src.loaders.config import Config

# Create config object
config = Config('../config')

# make a sql connection
# use temporary db
config.database = '../data/boardgames.sqlite3'
sql_db = sqlite3.connect(config.database)

In [5]:
def is_everything_imported(df, table: str, db):
    '''
    Checking is number of rows in dataframe == number of rows in SQL table
    Return True or False
    '''
    cursor = db.cursor()
    num_of_cols_in_sql_q = f"""
    SELECT COUNT(*)
    FROM pragma_table_info('{table}');
    """
    num_of_rows_in_sql_q = f"""
    SELECT COUNT(*)
    FROM {table};
    """
    num_of_cols_in_sql = cursor.execute(num_of_cols_in_sql_q).fetchall()[0][0]
    num_of_rows_in_sql = cursor.execute(num_of_rows_in_sql_q).fetchall()[0][0]  
    return df.shape == (num_of_rows_in_sql, num_of_cols_in_sql)


def read_sql_table_to_df(table: str, db):
    '''
    Read table from SQL db to pandas Dataframe
    '''
    df = pd.read_sql_query(f'SELECT * FROM {table}', db)
    if not is_everything_imported(df, table, db):
        raise ValueError ('Error while importing sql to dataframes, rows in dataframs != rows in sql table')
    return df

In [77]:
# Reading all sql tables to dataframes
df_game = read_sql_table_to_df('game', sql_db)
df_category = read_sql_table_to_df('category', sql_db)
df_game_category_map = read_sql_table_to_df('game_category_map', sql_db)
df_game_mechanic_map = read_sql_table_to_df('game_mechanic_map', sql_db)
df_mechanic = read_sql_table_to_df('mechanic', sql_db)

In [108]:
# df_category = df_category.rename(columns={'Name':'CategoryName'})

# df_gameid_cat = df_game_category_map.merge(
#     df_category,
#     left_on='CategoryID',
#     right_on='ID'
# ).drop(columns=['MapID','ID', 'CategoryID'])

# df_gameid_cat_piv = df_gameid_cat.pivot(
#     index='GameID',
#     columns='CategoryName',
#     values='CategoryName'
# )

# df = df_game.merge(df_gameid_cat_piv,
#     left_on='ID',
#     right_on='GameID'
# )

# print(df.shape, df_game.shape) # 9 games dissapered

(1991, 96) (2000, 13)

In [110]:
# df_mechanic = df_mechanic.rename(columns={'Name':'MechanicName'})

# df_mech_id = df_mechanic.merge(df_game_mechanic_map,
#     left_on='ID',
#     right_on='MechanicID'
# )

# df_mech_id_piv = df_mech_id.pivot(
#     index='GameID',
#     columns='MechanicName',
#     values='MechanicName'
# )

# df = df_game.merge(df_mech_id_piv,
#     left_on='ID',
#     right_on='GameID'
# )

# print(df.shape, df_game.shape) # 9 games dissapered

(1992, 194) (2000, 13)

In [111]:
df.head(15)

,ID,Title,ReleaseYear,AvgRating,BayesRating,TotalRatings,StdRatings,MinPlayers,MaxPlayers,MinPlaytime,...,turn-order-stat-based,variable-phase-order,variable-player-powers,variable-set,victory-points-resource,voting,worker-placement,worker-placement-dice-workers,worker-placement-different-worker-types,zone-control
0,1,Die Macher,1986,7.60990,7.08758,5496,1.58139,3,5,240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Samurai,1998,7.45896,7.23663,15497,1.18684,2,4,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,Acquire,1964,7.33699,7.13433,19080,1.33709,2,6,90,...,NaN,NaN,NaN,NaN,victory-points-resource,NaN,NaN,NaN,NaN,NaN
3,10,Elfenland,1998,6.69245,6.46683,8505,1.25169,2,6,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,Bohnanza,1997,7.04414,6.93482,41442,1.29206,2,7,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,12,Ra,1999,7.49112,7.31736,20309,1.33627,2,5,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,13,CATAN,1995,7.12288,6.95487,112595,1.48533,3,4,60,...,NaN,NaN,NaN,variable-set,NaN,NaN,NaN,NaN,NaN,NaN
7,15,Cosmic Encounter,1977,6.91244,6.41563,3916,1.82543,2,6,90,...,NaN,NaN,variable-player-powers,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,18,RoboRally,1994,7.07079,6.91903,23187,1.54099,2,8,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,22,Magic Realm,1979,7.24235,6.34974,2052,1.97471,1,16,240,...,NaN,NaN,variable-player-powers,variable-set,NaN,NaN,NaN,NaN,NaN,NaN
10,26,Age of Renaissance,1996,7.09672,6.32736,2161,1.74790,3,6,120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,41,Can't Stop,1980,6.86579,6.70754,15375,1.31011,2,4,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,42,Tigris & Euphrates,1997,7.70234,7.52828,26875,1.48645,2,4,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,45,Perudo,1800,6.90906,6.71970,13662,1.40529,2,6,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,46,Medici,1995,7.16305,6.83206,7631,1.25705,2,6,60,...,NaN,NaN,NaN,NaN,victory-points-resource,NaN,NaN,NaN,NaN,NaN